name: 'Install Ghostscript'
description: 'Install Ghostscript on all OS'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
runs:
  using: "composite"
  steps:
      - run: |
          if [ ${{ inputs.who-to-greet }} == "" ]; then
            echo "empty string "
          fi
          if [ "${{ inputs.who-to-greet }}" == "" ]; then
            echo "empty "
          fi
          echo "${{ inputs.who-to-greet }}"
      - if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install -y ghostscript
        shell: bash
      - if: ${{ runner.os == 'Windows' }}
        run: choco install ghostscript
        shell: pwsh
      - if: ${{ runner.os == 'macOS' }}
        run: brew install ghostscript
        shell: bash