name: 'Install Ghostscript'
description: 'Install Ghostscript on all OS'
runs:
  using: "composite"
  steps:
      - if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install -y ghostscript
      - if: ${{ runner.os == 'Windows' }}
        run: choco install ghostscript
        shell: powserhell
      - if: ${{ runner.os == 'macOS' }}
        run: brew install ghostscript