# This is a basic workflow to help you get started with Actions

name: test-cache-behavior

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  using-r:
    runs-on: ubuntu-20.04
    name: Test cache storage
    strategy:
      fail-fast: false
    env: 
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    steps:
      - uses: r-lib/actions/setup-r@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-1-${{ hashFiles(format('{0}/**/DESCRIPTION', env.R_LIBS_USER)) }}
          restore-keys: ${{ runner.os }}-1-
      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pak("glue")
        shell: Rscript {0}
