# This is a basic workflow to help you get started with Actions

name: test-quarto-setup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
      - run: |
          echo $PATH
          quarto --version
  quarto-linux-version:
    runs-on: ubuntu-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          version: 0.3.71
      - run: |
          echo $PATH
          quarto --version
  quarto-linux-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          version: 'pre-release'
      - run: |
          echo $PATH
          quarto --version
  quarto-linux-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          tinytex: true
      - run: |
          echo $PATH
          quarto --version
          quarto tools info tinytex
          tlmgr --version
  quarto-windows:
    runs-on: windows-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
      - run: |
          $env:PATH
          quarto --version
        shell: powershell
  quarto-windows-version:
    runs-on: windows-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          version: 0.3.71
      - run: |
          $env:PATH
          quarto --version
        shell: powershell
  quarto-windows-latex:
    runs-on: windows-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          tinytex: true
      - run: |
          $env:PATH
          quarto --version
          quarto tools info tinytex
          tlmgr --version
        shell: powershell
  quarto-macos:
    runs-on: macos-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
      - run: |
          echo $PATH
          quarto --version
  quarto-macos-version:
    runs-on: macos-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          version: 0.3.71
      - run: |
          echo $PATH
          quarto --version
  quarto-macos-prerelease:
    runs-on: macos-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          version: 'pre-release'
      - run: |
          echo $PATH
          quarto --version
  quarto-macos-latex:
    runs-on: macos-latest
    steps:
      - uses: cderv/quarto-action/setup@prerelease-support
        with:
          tinytex: true
      - run: |
          echo $PATH
          quarto --version
          quarto tools info tinytex
          tlmgr --version