name: test-julia-install
on: [workflow_dispatch]

jobs:
  install:
    runs-on: windows-latest
    name: Test Julia install on windows
    steps:
      - uses: actions/checkout@v4
      - run: $env:PATH -Split ";"
        shell: powershell
      - run: gcm tar
        shell: powershell
      - uses: r-lib/actions/setup-r@v2
        # uncomment the following line to fix julia setup 
        # but it will have side effect probably on R setup
        # with:
        #  windows-path-include-rtools: false
      - run: $env:PATH -Split ";"
        shell: powershell
      - run: gcm tar
        shell: powershell
      - uses: julia-actions/setup-julia@v1
        env:
          TAR_OPTIONS: --force-local
        with:
          version: '1.10'