name: test chromote
on: [workflow_dispatch]

jobs:
  screenshot:
    runs-on: ubuntu-20.04
    name: Test chromote
    strategy:
      fail-fast: false
    env: 
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    steps:
      - uses: r-lib/actions/setup-r@v1

      - name: install requirements
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pak("webshot2")
        shell: Rscript {0}
        
      - name: scrennshot
        run: webshot2::webshot("https://cran.r-project.org/")
        shell: Rscript {0}
