name: test-quarto

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.87

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          path: ${{ github.workspace }}/quarto/quarto-project
