# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  push:
    branches: [main]
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - env:
          TEST: "$(git log --format=%B --no-merges -n 1)"
        run: echo $TEST
