on:
  workflow_dispatch:
  workflow_call:
    inputs:
      prerelease:
        required: true
        description: 'Whether to deploy prerelease or release site'
        type: boolean
        default: false

name: workflow-call

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - if: (inputs.prerelease != null && inputs.prerelease == false) || github.event_name == 'workflow_dispatch'
        run: |
          echo "${{ toJson(inputs) }}"
          echo "${{ toJson(inputs.prerelease) }}"
      - if: (inputs.prerelease != null && inputs.prerelease == true) || github.event_name == 'workflow_dispatch'
        run: |
          echo "${{ toJson(inputs) }}"
      - if: inputs.prerelease == null
        run: |
          echo "${{ toJson(inputs) }}"
