# This is a basic workflow to help you get started with Actions

name: test-pandoc-setup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  pandoc-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: cderv/actions/setup-pandoc-nightly@nightly-pandoc
      - run: |
          echo $PATH
          pandoc --version
  pandoc-windows:
    runs-on: windows-latest
    steps:
      - uses: cderv/actions/setup-pandoc-nightly@nightly-pandoc
        with:
          os: windows
      - run: |
          echo $env:PATH
          pandoc.exe --version
