# This is a basic workflow to help you get started with Actions

name: test-chrome-finding

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  chrome-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Chromium'
        run: |
          echo $(which chromium-browser)
          $(which chromium-browser) --headless https://www.chromestatus.com
  chrome-windows:
    runs-on: windows-latest
    steps:
      - name: 'Check Chromium'
        run: |
          echo $(which chromium-browser)
          $(which chromium-browser) --headless https://www.chromestatus.com
        shell: cmd
  chrome-macos:
    runs-on: macos-latest
    steps:
      - name: 'Check Chromium'
        run: |
          echo $(which chromium-browser)
          $(which chromium-browser) --headless https://www.chromestatus.com