name: test

on: [workflow_dispatch]

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:      
      - run: gh --version
        
      - name: update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download -R cli/cli

      - run: ./gh --version