name: test

on: [workflow_dispatch]

jobs:
  brew:
    runs-on: ubuntu-latest
    steps:      
      - run: gh --version
        
      - name: update
        run: |
          brew update
          brew install gh

      - run: which gh

      - run: brew --prefix gh

      - run : ls $(brew --prefix gh)/bin

      - run: $(brew --prefix gh)/bin/gh --version

  release:
    runs-on: ubuntu-latest
    steps:      
      - run: gh --version
        
      - name: update
        run: |
          gh release download -R cli/cli --pattern '*linux_386.deb'
          sudo dpkg -i $(ls *.deb)

      - run: which gh

      - run: gh --version