name: test

on: [workflow_dispatch]

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:      
      - run: gh --version
        
      - name: update
        run: |
          brew install gh

      - run: which gh

      - run: brew --prefix gh

      - run : ls $(brew --prefix gh)/bin

      - run: $(brew --prefix gh)/bin/gh --version