name: test-quarto

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: gaborcsardi/quarto-actions/setup@fix/setup-runner-temp

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@main
        with: 
          path: quarto/quarto-project
  build-deploy-2:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: gaborcsardi/quarto-actions/setup@fix/setup-runner-temp

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@main
        with: 
          path: quarto/quarto-project
  build-deploy-3:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: gaborcsardi/quarto-actions/setup@fix/setup-runner-temp

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@main
        with: 
          path: quarto/quarto-project