name: test

on: [workflow_dispatch]

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:      
      - run: gh --version
        
      - name: update
        run: |
          sudo apt-get update
          sudo apt-get upgrade gh

      - run: gh --version