# This is a basic workflow to help you get started with Actions

name: test-install-ghostscript

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/install-ghostscript
      - run: ghostscript --version
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/install-ghostscript
      - run: ghostscript --version
  macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/install-ghostscript
      - run: ghostscript --version
