# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  push:
    branches: [main]
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/setup-r@v1
          
      - name: what is tempdir ?
        run: tempdir()
        shell: Rscript {0}
        
      - name: what is tempdir if we change ?
        env:
          TMPDIR: ${{ runner.temp }}
        run: tempdir()
        shell: Rscript {0}
