# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  push:
    branches: [main]
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: r-lib/actions/setup-r@v1
      
      - name: Add some R options for later steps
        run: |
          cat(readLines("~/.Rprofile"), sep = "\n")
          cat("\noptions(tinytex.verbose = TRUE)\n", file = "~/.Rprofile", append = TRUE)
          cat(readLines("~/.Rprofile"), sep = "\n")
        shell: Rscript {0}
      
      - run: | 
          getOption('tinytex.verbose')
          getOption('crayon.enabled')
        shell: Rscript {0}
      
