on:
  workflow_dispatch:

name: calling-workflow-call

jobs:
  test-inputs:
    uses: ./.github/workflows/test-workflow-call.yaml
    with:
      prerelease: true
  test-inputs2:
    uses: ./.github/workflows/test-workflow-call.yaml
    with:
      prerelease: false
      
