on:
  push:
    branches:
      - main
      - master
    paths: .github/workflows/tinytex-base.yaml

name: check required LateX packages

jobs:
  test-path:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-base.sh
          chmod +x install-base.sh
          ./install-base.sh
          pwd
          ls
          mv texlive ../../
          ls ../../
          echo $PATH
          ../../texlive/bin/*/tlmgr path add
          echo $PATH
