# This is a basic workflow to help you get started with Actions

name: test-tinytex-bin-powershell

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  tinytex-windows:
    runs-on: windows-latest
    steps:
      - uses: cderv/actions/setup-tinytex@new-tinytex-setup
        env:
          TINYTEX_INSTALLER: TinyTeX
      - name: check tlmgr installation
        run: |
          echo $env:PATH
          tlmgr --version
