# This is a basic workflow to help you get started with Actions

name: test-tinytex-bin

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  tinytex-action:
    strategy:
      fail-fast: false
      matrix:
        bundle: [TinyTeX, TinyTeX-1, TinyTeX-2]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: ${{ matrix.bundle}}
      - run: echo $PATH
        shell: bash
      - name: check tlmgr installation
        run: |
          which tlmgr
        shell: bash
        
  tinytex-windows-script:
    strategy:
      fail-fast: false
      matrix:
        bundle: [TinyTeX, TinyTeX-1, TinyTeX-2]
    runs-on: windows-latest
    steps:
      - name: install tinytex
        env:
          TINYTEX_INSTALLER: ${{ matrix.bundle }}
        run: |
          powershell -Command "Invoke-WebRequest https://raw.githubusercontent.com/cderv/tinytex/main/tools/install-bin-windows.bat -OutFile install-bin-windows.bat"
          install-bin-windows.bat
        shell: cmd
      - run: ls $env:APPDATA
      - name: check tlmgr installation
        run: |
          echo $env:PATH
          $env:APPDATA/TinyTeX/bin/win32/tlmgr --version

  tinytex-r-package:
    strategy:
      fail-fast: false
      matrix:
        bundle: [TinyTeX, TinyTeX-1, TinyTeX-2]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.bundle }} - ${{ matrix.os }}
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: rstudio/tinytex
      - name: install tinytex
        run: |
          tinytex::install_tinytex(bundle = "${{ matrix.bundle }}", version= "daily-github")
        shell: Rscript {0}
      - run: ls $env:APPDATA
        shell: bash
      - run: echo $PATH
        shell: bash
      - name: check tlmgr installation
        run: |
          which tlmgr
        shell: bash