# This is a basic workflow to help you get started with Actions

name: test-tinytex-bin-powershell

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

jobs:
  tinytex-windows-action:
    if: false
    runs-on: windows-latest
    steps:
      - uses: cderv/actions/setup-tinytex@new-tinytex-setup
        env:
          TINYTEX_INSTALLER: TinyTeX
      - name: check tlmgr installation
        run: |
          echo $env:PATH
          tlmgr --version
  tinytex-windows-script:
    runs-on: windows-latest
    steps:
      - name: Download install script
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/cderv/tinytex/main/tools/install-bin-windows.bat -OutFile install-bin-windows.bat
        shell: pwsh
      - name: Run install
        env:
          TINYTEX_INSTALLER: TinyTeX-2
        run: |
          install-bin-windows.bat
        shell: cmd
      - run: ls $env:APPDATA
      - name: check tlmgr installation
        run: |
          echo $env:PATH
          $env:APPDATA/TinyTeX/bin/win32/tlmgr --version

  tinytex-windows-package:
    if: false
    runs-on: windows-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: cderv/tinytex
      - name: install tinytex
        run: |
          tinytex::install_tinytex(bundle = "TinyTeX-2", version= "daily-github")
        shell: Rscript {0}
      - run: ls $APPDATA
        shell: bash
      - name: check tlmgr installation
        run: |
          echo $PATH
          tlmgr --version
        shell: bash
