on:
  push:
    branches:
      - main
      - master

name: check required LateX packages

jobs:
  test-path:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-base.sh
          chmod +x install-base.sh
          ./install-base.sh
          pwd
          ls
          ls ~
